//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerCompanyApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembling
    {
        public int ID_Technique { get; set; }
        public int ID_Component { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Technique Technique { get; set; }
    }
}
