//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerCompanyApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int ID { get; set; }
        public int ID_Dealer { get; set; }
        public int ID_Component { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_DealStatus { get; set; }
        public decimal Price { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual DealStatus DealStatus { get; set; }
    }
}
